amino_chain='MFMFRKSNQTSKFWLGLWSLKREHTHENKRPRNWIDFPTCYPPNSVEEVWSYCHRLGNQSRKMQRYCFLPIQKHKGKLVNEEWCQAFHCYRWMKHLRMEFRMGMPGVTHGGHFSVYVFPKMTDKNMAISHAAWMAQPMKHQWRLEEWPAFELQMICQAQHNLASFRIQFHFVHRQNVMDLAPHCWKQVNTGAVPAEQYGNVQKNVRLQVYSYDPETCTGKVLRPIIWNCQNTQVHWSWASQFIHCALSKPTSIFWAANTGMIRGITKHPNFYDQGTPLDHIEPDTIMTWIQRTCVCMPGHIWYSHMWGQSQRGQSEEPMNWHPKGMQICMVFITFAYQVNKRDKQYESRIKTDDWSILCVTDEMHAWAIRYYFKKCKISYFVCPTEKFQFMFNSIHTSIEHLNDDMKPNHNQNKHKMRNMILAMPTYDAWFIMPLFFRSKFTSIGLSGMCNGGCWYGKMYHCTLADKPVMDHRQNHWYDCRYNDMSSEVLYEKPPWQMGQWFDECFKKQEGCWEMKNDALQWVADFFVTSGELGWFALEYMAEFSGLVMAVIIQYYYPSHKKYEWEYHKMDSMAPNWEERGPFRDAVHCQGGVMDPYMECVWGRNCLHYKWLRVQCWRYVPWSRFLIWGQVMSFVAIVWQAIRPKLERLNTVARPMKASHPGRKTYHIPCIATRELPGQPGKPNKVPQWAIENRDCSARFCEVNHFAAWMDGGQNSFPWHIKCGQFVKVIVFDYIDFENCSYQQCLQIQFQSVNQHRLYQCHAWMGMNELNPDYQGHVIPHVETPRFIVVNKSDHNCLDFYYSERCEWMGAEAACKAYEYYDNHCWYTSRLFKTCWIQAVREAFYCNTWDLFNRHKEPTKDALKIVLQLGGRQNGMCAYSGARTNNCGAYIIDRKWCWHDWVQGEVGYQQCAKAKYTVRYRGMTHRKWMFESTVYDRDSQIARNCVIEPGITGPNCYHRIQECTCPGQGNGYYDMKKVADWEPPGMQMIKTCEFNRNCK'
def rosmrna(aminoacids):
    prot_dic = {'F': ['UUU', 'UUC'],
              'L': ['UUA', 'UUG', 'CUU', 'CUC', 'CUA', 'CUG'],
              'S': ['UCU', 'UCC', 'UCA', 'UCG', 'AGU', 'AGC'],
              'Y': ['UAU', 'UAC'],
              '*': ['UAA', 'UAG', 'UGA'],
              'C': ['UGU', 'UGC'],
              'W': ['UGG'],
              'P': ['CCU', 'CCC', 'CCA', 'CCG'],
              'H': ['CAU', 'CAC'],
              'Q': ['CAA', 'CAG'],
              'R': ['CGU', 'CGC', 'CGA', 'CGG', 'AGA', 'AGG'],
              'V': ['GUU', 'GUC', 'GUA', 'GUG'],
              'A': ['GCU', 'GCC', 'GCA', 'GCG'],
              'D': ['GAU', 'GAC'],
              'E': ['GAA', 'GAG'],
              'G': ['GGU', 'GGC', 'GGA', 'GGG'],
              'I': ['AUU', 'AUC', 'AUA'],
              'M': ['AUG'],
              'T': ['ACU', 'ACC', 'ACA', 'ACG'],
              'N': ['AAU', 'AAC'],
              'K': ['AAA', 'AAG']}
    number = 1
    for i in aminoacids:
        number = number * len(prot_dic[i])
    number = number*len(prot_dic["*"])
    return number % 1000000

print(rosmrna(amino_chain))